ALTER TABLE public.listings
  ADD COLUMN IF NOT EXISTS tagline text,
  ADD COLUMN IF NOT EXISTS long_description text,
  ADD COLUMN IF NOT EXISTS about_property text,
  ADD COLUMN IF NOT EXISTS about_area text,
  ADD COLUMN IF NOT EXISTS highlights text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS sqm integer,
  ADD COLUMN IF NOT EXISTS property_type text DEFAULT 'summerhouse',
  ADD COLUMN IF NOT EXISTS weekend_price_per_night integer,
  ADD COLUMN IF NOT EXISTS min_nights integer DEFAULT 2,
  ADD COLUMN IF NOT EXISTS deposit integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS channel_airbnb_ready boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS channel_booking_ready boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS channel_vrbo_ready boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS channel_airbnb_title text,
  ADD COLUMN IF NOT EXISTS channel_booking_title text,
  ADD COLUMN IF NOT EXISTS channel_vrbo_title text,
  ADD COLUMN IF NOT EXISTS channel_airbnb_description text,
  ADD COLUMN IF NOT EXISTS channel_booking_description text,
  ADD COLUMN IF NOT EXISTS channel_vrbo_description text,
  ADD COLUMN IF NOT EXISTS readiness_score integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS internal_status text DEFAULT 'draft',
  ADD COLUMN IF NOT EXISTS checkin_info text,
  ADD COLUMN IF NOT EXISTS checkout_info text,
  ADD COLUMN IF NOT EXISTS image_captions jsonb DEFAULT '{}';