
ALTER TABLE public.listings
  ADD COLUMN IF NOT EXISTS intro_title text,
  ADD COLUMN IF NOT EXISTS intro_paragraph_1 text,
  ADD COLUMN IF NOT EXISTS intro_paragraph_2 text,
  ADD COLUMN IF NOT EXISTS intro_features jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS property_bullets text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS comfort_title text,
  ADD COLUMN IF NOT EXISTS comfort_intro text,
  ADD COLUMN IF NOT EXISTS comfort_blocks jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS access_title text,
  ADD COLUMN IF NOT EXISTS access_intro text,
  ADD COLUMN IF NOT EXISTS access_smart_lock text,
  ADD COLUMN IF NOT EXISTS access_code text,
  ADD COLUMN IF NOT EXISTS access_parking text,
  ADD COLUMN IF NOT EXISTS access_arrival text,
  ADD COLUMN IF NOT EXISTS included_title text,
  ADD COLUMN IF NOT EXISTS included_intro text,
  ADD COLUMN IF NOT EXISTS included_items text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS bring_yourself_items text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS purchasable_items text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS extras_title text,
  ADD COLUMN IF NOT EXISTS extras_intro text,
  ADD COLUMN IF NOT EXISTS extras_upsell_items text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS extras_pricing_notes text,
  ADD COLUMN IF NOT EXISTS bedroom_cards jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS highlighted_amenities text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS amenities_button_text text DEFAULT 'Vis alle faciliteter',
  ADD COLUMN IF NOT EXISTS area_title text,
  ADD COLUMN IF NOT EXISTS area_distances jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS area_attractions jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS area_image text,
  ADD COLUMN IF NOT EXISTS reviews_title text,
  ADD COLUMN IF NOT EXISTS reviews_rating numeric,
  ADD COLUMN IF NOT EXISTS reviews_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reviews_badges text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS reviews_entries jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS contact_title text,
  ADD COLUMN IF NOT EXISTS contact_name text,
  ADD COLUMN IF NOT EXISTS contact_role text,
  ADD COLUMN IF NOT EXISTS contact_image text,
  ADD COLUMN IF NOT EXISTS contact_text text,
  ADD COLUMN IF NOT EXISTS contact_email text,
  ADD COLUMN IF NOT EXISTS contact_phone text,
  ADD COLUMN IF NOT EXISTS contact_cta_primary text DEFAULT 'Kontakt os',
  ADD COLUMN IF NOT EXISTS contact_cta_secondary text,
  ADD COLUMN IF NOT EXISTS sticky_bar_logo text,
  ADD COLUMN IF NOT EXISTS sticky_bar_price_label text DEFAULT 'Fra',
  ADD COLUMN IF NOT EXISTS sticky_bar_cta text DEFAULT 'Book nu',
  ADD COLUMN IF NOT EXISTS sticky_bar_payment_icons text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS hero_rating numeric,
  ADD COLUMN IF NOT EXISTS hero_review_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS hero_booking_cta text DEFAULT 'Book denne bolig',
  ADD COLUMN IF NOT EXISTS hero_booking_subtext text,
  ADD COLUMN IF NOT EXISTS hero_rarity_badge text,
  ADD COLUMN IF NOT EXISTS hero_clickbait_title text,
  ADD COLUMN IF NOT EXISTS hero_hook_description text,
  ADD COLUMN IF NOT EXISTS hero_extra_note text,
  ADD COLUMN IF NOT EXISTS seo_title text,
  ADD COLUMN IF NOT EXISTS seo_description text,
  ADD COLUMN IF NOT EXISTS seo_image text,
  ADD COLUMN IF NOT EXISTS image_channel_visibility jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS video_button_text text DEFAULT 'Se video',
  ADD COLUMN IF NOT EXISTS floorplan_button_text text DEFAULT 'Se plantegning',
  ADD COLUMN IF NOT EXISTS contact_button_text text DEFAULT 'Kontakt vært',
  ADD COLUMN IF NOT EXISTS internal_notes text;
